### ISSUE TITLE
Update @lezer/common and @lezer/lr

### ISSUE THREAD

**Issue by joegar000** [mischnic/json-sourcemap#1]
I'm working on a project that utilizes both the [CodeMirror](https://codemirror.net/) editor and Parcel. Since both CodeMirror and Parcel utilize the lezer parser system, Parcel's older version of [@lezer/common](https://github.com/lezer-parser/common) is conflicting with the current version of @lezer/common that I need for my project. Any help is appreciated, thanks!

**Comment by karlhorky** [comment]
@mischnic what do you think about upgrading to `^1.0.0` of both `@lezer/common` and `@lezer/lr` and then releasing as a patch version?

This would allow people with existing transitive dependencies to upgrade without other depending packages having to release new versions...

**Comment by karlhorky** [comment]
@mischnic To be clear about the problem, if other packages such as CodeMirror use modern versions of `@lezer/common` and `@lezer/lr`, then things like syntax highlighting will break, as mentioned below (which is a problem that can easily make it to production without someone noticing):

- https://github.com/uiwjs/react-codemirror/issues/216
- https://github.com/codemirror/dev/issues/666

There are workarounds with Yarn Resolutions or npm/pnpm Overrides mentioned in the issues above, but it would be great if `@mischnic/json-sourcemap` used a modern version of `@lezer/common` and `@lezer/lr` out of the box.

**Comment by mischnic** [comment]
I'll try to do this soon. Last time I tried I ran into some problems when upgrading https://github.com/mischnic/parcel-transformer-lezer (used here to build this package) to use lezer 1.x

**Comment by mischnic** [comment]
0.1.1 is published, let's hope I didn't break anything.

**Comment by karlhorky** [comment]
Running the updated version in production now (via `@parcel/core` via `gatsby`), no complaints yet :)
